// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package app_search

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "app_search", asset.ModuleFieldsPri, AssetAppSearch); err != nil {
		panic(err)
	}
}

// AssetAppSearch returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/app_search.
func AssetAppSearch() string {
	return "eJzk10tu2zAQBuC9TzHIPj6AFwWCdtEWSFC0QLtURuJvmYn4CB9OdPuCUuzKshU5LmwVKJe0PPNxSFHkNT2iXhBbm3mwK1YzoiBDhQVd/em8mhE5VGCPBeUIPCMS8IWTNkijF/RhRkSdKKSMiBVmREuJSvhF8/s1aVboZUst1BYLKp2J9rXnQPTdWN14PnDw295D4VLrD2DTDqZq24219KMdUD9H39L1PKzVTv+QaCR7al9/3u6lHkrfJSgo4+osei6x99BbniNMqd028Wko/hCvS1yBbSa1DPO8DugPcFdaGV0OPHAENrXPYEspG0UPQXlNYYWmvFJTA5iPa9NfL6UVfwMtjFIyhAtpPzbZIJrcFMwpYsUvF7He8kvLHKrum1RtdHbZdXtn9PV27UquXt/sExfH1n/ZBbIdRLFZKe8axUb/FBH3rCdvrb+Me4Q7HHRse2XNVR1k4TOsoYOfFybqMLjRDlTwiOrdRZXDkVmShRZSl/Rgcp/qlEp233fct8PZXwQbuDBFVNAhE/DBmRpuKvq+ZBQPXUqN6el9xyhcaoGXjIWYztwhHMeFyIQpMgdl1hOzdymjfMWymk7cZh9FOiwd/CrbvgYNd7KNZIBzxDDaGZqs3FvAKNUXKyjOohUcpvPuKkbRy7SaxAWwbaLW+swyJHgwlIMcgpMQhz/JDk8Rfu96cvJH+Xsbj1RKWrz3s3z+MjkU0CGdY2yFdJAZKED3sivnIjpO8c9xE7v59oUcvDXag4JUGKgdHXkt43U5V+c+EN6s4bhEDy41KVlV0qMwWrx9Ek/3hbMz02XhfcQN7xn5WWf9E/tVbtiJ/3LuwfpfmPzfAQAA//9I8c4f"
}
